// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: gocachepb.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoCache_Get_FullMethodName = "/gocachepb.GoCache/Get"
)

// GoCacheClient is the client API for GoCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type goCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGoCacheClient(cc grpc.ClientConnInterface) GoCacheClient {
	return &goCacheClient{cc}
}

func (c *goCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, GoCache_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoCacheServer is the server API for GoCache service.
// All implementations must embed UnimplementedGoCacheServer
// for forward compatibility
type GoCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedGoCacheServer()
}

// UnimplementedGoCacheServer must be embedded to have forward compatible implementations.
type UnimplementedGoCacheServer struct {
}

func (UnimplementedGoCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGoCacheServer) mustEmbedUnimplementedGoCacheServer() {}

// UnsafeGoCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoCacheServer will
// result in compilation errors.
type UnsafeGoCacheServer interface {
	mustEmbedUnimplementedGoCacheServer()
}

func RegisterGoCacheServer(s grpc.ServiceRegistrar, srv GoCacheServer) {
	s.RegisterService(&GoCache_ServiceDesc, srv)
}

func _GoCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoCache_ServiceDesc is the grpc.ServiceDesc for GoCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gocachepb.GoCache",
	HandlerType: (*GoCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GoCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gocachepb.proto",
}
